branch-defaults:
  default:
    environment: Udagram-be-duongntt1-env
environment-defaults:
  Udagram-be-duongntt1-env:
    branch: null
    repository: null
global:
  application_name: udagram-be-duongntt1
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
